services:

  mysql:
    image: mysql:8.0
    container_name: noteshub-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: noteshub
      MYSQL_USER: noteshub
      MYSQL_PASSWORD: password123
    volumes:
      - mysql_data:/var/lib/mysql

  flask:
    build: .
    container_name: noteshub-app
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mysql

volumes:
  mysql_data:

